### PR TITLE
Model interaction improvements

### PR DESCRIPTION
**Pull request by k0na**
These changes resolve the model issues that have been raised.

**Fix valid cache models yielding invalid points edge case**
No longer assume points retrieved from valid cache models are correct;
only return if not (-1,-1) and otherwise use bounding model as fallback.

**Support scaling of NPC models**
Fits models that are reused across multiple npcs to size, for example,
cow and cow calves share the same model but have different interactable
bounds.

### CODE REVIEW

**Comment by ChrisBPB** [comment]
please don't merge this before .18 is release and testing is done

**Comment by k0na** [comment]
Agreed @ChrisBPB, I've marked the pull request as a draft for that exact reason

**Comment by k0na** [comment]
The changes work fine on my computer but I would appreciate if someone could git checkout the `model-interactions` branch and verify on their end before we merge this.

**Comment by Paris** [comment]
Hey @k0na could you reserve the merge conflicts when you have the time.

**Comment by Strikegently** [comment]
Everything seems good. I'm going to merge this. I have a change I'd like to see, but it's in the client code you can't access so I can make it.

**Pull request merged**
